import java.awt.*; // Contains Classes and interfaces that are used to Create GUI in java.
import java.awt.event.*; /*Contains Classes and interfaces that are used to listen for and
respond to events generated by AWT Components*/

public class UnitConvertor {

    Label detail,labl,labl1,labl2,labl3,disp,disp1,disp2;
    TextField val,unit;
    Button convtButton, refreshButton;

    UnitConvertor(){

    //Gnrl labels
        detail = new Label("Conversion of Temperature Units between Celsius, Kelvin and Fahrenheit Scales");
        detail.setAlignment(Label.LEFT);
        detail.setBounds(40,50,550,30);
        detail.setFont(new Font("TimesNewRoman",Font.BOLD,13));

        labl = new Label("Enter the value and then its Units : ");
        labl.setBounds(70,100,250,30);
        labl.setFont(new Font("TimesNewRoman", Font.PLAIN,13));

        labl1 = new Label("Enter K- for Kelvin");
        labl1.setBounds(150,145,120,20);

        labl2 = new Label("Enter C- for Celsius");
        labl2.setBounds(150,170,120,20);

        labl3 = new Label ("Enter F- for Fahrenheit");
        labl3.setBounds(150,195,130,20);

    //TextField
        val = new TextField("Enter Digits");
        val.setBounds(330,150,100,25);
        //addFL - is Used to make it like a placeholder in this
        val.addFocusListener(new FocusListener() {
            public void focusGained(FocusEvent e){
                if(val.getText().equals("Enter Digits")){
                    val.setText("");
                }
            }
            public void focusLost(FocusEvent e){
                if(val.getText().equals("")){
                    val.setText("Enter Digits");
                }
            } 
        });

        unit = new TextField("Enter Unit");
        unit.setBounds(330,190,100,25);
        unit.addFocusListener(new FocusListener() {
            public void focusGained(FocusEvent e){
                if(unit.getText().equals("Enter Unit")){
                    unit.setText("");
                }
            }
            public void focusLost(FocusEvent e){
                if(unit.getText().equals("")){
                    unit.setText("Enter Unit");
                }
            } 
        });

    //Output Display labels
        disp = new Label("Conversion of Units : ");
        disp.setBounds(70,300,400,40);
        disp.setFont(new Font("TimesNewRoman",Font.PLAIN,13));

        disp1 = new Label("Equivalent Scale ");
        disp1.setBounds(150,350,350,40);

        disp2 = new Label("Equivalent Scale ");
        disp2.setBounds(150,400,350,40);

    //Convert Button 
        convtButton = new Button("Convert");
        convtButton.setBounds(330,250,100,40);
        ActionListener convert = new ActionListener()
        {
            public void actionPerformed(ActionEvent e){
                //if(character.isDigit(val))
                float value = Float.parseFloat(val.getText());  
                String str =  unit.getText();
                char symbol = str.charAt(0);

                methodConvert(value, symbol);
            }
        };
        convtButton.addActionListener(convert);

    //Refresh Button
        refreshButton = new Button("Refresh");
        refreshButton.setBounds(160,250,100,40);
        ActionListener refresh = new ActionListener()
        {
            public void actionPerformed(ActionEvent e){
                val.setText("Enter Digits");  
                unit.setText("Enter Unit");
                disp.setText("Conversion of Units");
                disp1.setText("Equivalent Scale");
                disp2.setText("Equivalent Scale ");               
            }
        };
        refreshButton.addActionListener(refresh);

    //Creating a instance for Frame
        Frame f = new Frame();
    //adding to frame 
        f.add(detail);    //Used to Display : General Info's
        f.add(labl);       
        f.add(labl1);
        f.add(labl2);
        f.add(labl3);
        f.add(val);       //Used to get input values
        f.add(unit);      //Used to get Unit of the value
        f.add(refreshButton); 
        f.add(convtButton);
        f.add(disp);      //Used to Display the Outputs
        f.add(disp1);
        f.add(disp2);
        
    //Frame Details
        f.setSize(600,500);
        f.setTitle("Temperature Unit Convertor");
        f.setLayout(null);
        f.setVisible(true);
 
    //ForFrame-Windowlister to close
        f.addWindowListener(new WindowAdapter(){
            public void windowClosing(WindowEvent e){
                System.exit(0);
            }
        });

    }
//Method to Convert
    void methodConvert(float val, char unit)
    {
        float conv1,conv2;
        switch (unit)
        {
        case 'c':
        case 'C': 
            disp.setText("Temperature Conversion of Celsius to Fahrenheit & Kelvin scales");
        //Celsius to Fahrenheit: (0 C = 32 F)
            conv1 = (val*9/5)+32;
            disp1.setText("Equivalent Fahrenheit scale is :  "+conv1+" F");
        //Celsius to Kelvin: (0 C = 273.15k)
            conv2 = (val+273.15f);
            disp2.setText("Equivalent Kelvin scale is :  "+ conv2 + " K");
            break;
        
        case 'f':
        case 'F': 
            disp.setText("Temperature Conversion of Fahrenheit to Celsius & Kelvin scales");
        //Fahrenheit to Celsius: (32 F = 0 C)
            conv1 = (val - 32)*5/9;
            disp1.setText("Equivalent Celsius scale is :  "+conv1+ " C");
        //Fahrenheit to Kelvin: (32 F = 273.15 K)
            conv2 = (val-32)*5/9 + 273.15f;
            disp2.setText("Equivalent Kelvin scale is :  "+conv2+" K");
            break;
        
        case 'k':
        case 'K': 
            disp.setText("Temperature Conversion of Kelvin to Fahrenheit & Celsius scales");
        //Kelvin to Fahrenheit : (0 K = -459.67 F)
            conv1 = (val - 273.15f)*9/5 + 32;
            disp1.setText("Equivalent Fahrenheit scale is :  "+conv1+" F");
        //Kelvin to Celsius: (0 K = -273.15 C)
            conv2 = val-273.15f;
            disp2.setText("Equivalent Celsius scale is :  "+conv2+" C");
            break;
        
        default:
            disp1.setText("Error ! Check the entered details");
            disp2.setText("Note: enter only from the Above characters to represent it's Unit");
            break;
        }
    }    
    public static void main(String [] args){
        new UnitConvertor();
    }
    
}